###############################################################################
# MALO Risk Prediction — Shiny App
# Random Survival Forest (competing risks) for Major Adverse Liver Outcomes
#
# HOW A SHINY APP WORKS — three-paragraph orientation for new users
# ─────────────────────────────────────────────────────────────────
# A Shiny app is split into two pieces that talk to each other:
#
# 1.  ui  (User Interface) — defines the *layout and widgets* the browser
#     shows.  Think of it as the HTML template: input controls on the left,
#     output placeholders on the right.  It runs once, when the page loads.
#
# 2.  server — contains the *R logic* that runs in response to user actions.
#     Every time the user clicks a button or changes a slider, Shiny re-runs
#     the relevant reactive blocks inside server and pushes new values into
#     the output placeholders defined in ui.
#
# The call shinyApp(ui, server) at the bottom ties them together.
#
# REQUIRED FILES (must be in the same folder as app.R)
# ─────────────────────────────────────────────────────
#   RSF_final_clinical_model.rds  — saved with saveRDS() in BFA01.1.2
#   background_data.rds           — generated by generate_background.R
###############################################################################


# ── 1.  Packages ──────────────────────────────────────────────────────────────
# shiny:           the web-app framework
# bslib:           Bootstrap 5 theme helpers (cards, layouts, colour themes)
# randomForestSRC: the package the RSF model was trained with — needed to call
#                  predict() on the saved model object
# kernelshap:      model-agnostic Kernel SHAP values (replaces shapr/fastshap)
# dplyr:           data-wrangling (filter, mutate, etc.)
library(shiny)
library(bslib)
library(randomForestSRC)
library(kernelshap)
library(dplyr)

# ── 2.  Load heavy objects at start-up (OUTSIDE the server function) ──────────
# Placing readRDS() here means R loads the model into memory *once* when the
# app process starts, and then shares that single copy across all user
# sessions.  If you put it inside server(), every new visitor would re-read
# the 1 GB file — slow and wasteful.
#
# The model file is too large to ship with the app, so it is downloaded from
# Dropbox on first launch and cached locally for the lifetime of this process.
local({
  model_path <- file.path(tempdir(), "RSF_final_clinical_model.rds")
  if (!file.exists(model_path)) {
    message("Downloading RSF model from Dropbox (this may take a minute) …")
    download.file(
      url      = "https://www.dropbox.com/scl/fi/ulveqiv49gcx6jlydhtz7/RSF_final_clinical_model.rds?rlkey=50bkggvk08gagekozy4dlh9m1&st=w4ypd1cp&dl=1",
      destfile = model_path,
      mode     = "wb"
    )
    message("Download complete.")
  }
  message("Loading RSF model …")
  model <<- readRDS(model_path)
})

message("Loading SHAP background data …")
background <- readRDS("background_data.rds")
# background is a data.frame with 200–300 rows × 6 predictor columns,
# all stored as plain numbers (no factors).  It represents a sample of
# the training population and is used by shapr as the reference
# distribution when estimating each feature's marginal contribution.


# ── 3.  UI ────────────────────────────────────────────────────────────────────
# page_sidebar() gives a fixed left sidebar and a scrollable main area.
# All widget functions follow the pattern:
#   widgetType(inputId, label, ...)
# The inputId is the name you use in server to read the widget's value
# as input$<inputId>.

ui <- page_sidebar(
  title = "MALO Risk Prediction",
  theme = bs_theme(bootswatch = "flatly"),

  # ── Left sidebar: input controls ──────────────────────────────────────────
  sidebar = sidebar(
    width = 310,

    h5("Patient Characteristics", class = "mt-1 mb-3"),

    numericInput(
      inputId = "age",
      label   = "Age (years)",
      value   = 55, min = 18, max = 100, step = 1
    ),

    selectInput(
      inputId = "sex",
      label   = "Sex",
      choices = c("Male", "Female")
    ),

    numericInput(
      inputId = "bmi",
      label   = "BMI (kg/m²)",
      value   = 27.0, min = 10, max = 70, step = 0.1
    ),

    selectInput(
      inputId = "t2dm",
      label   = "Type 2 Diabetes",
      # The *value* sent to server is "0" or "1"; the *label* is what the
      # user sees in the drop-down.
      choices = c("No" = "0", "Yes" = "1")
    ),

    numericInput(
      inputId = "alcohol",
      label   = "Alcohol (standard drinks / week)",
      value   = 5, min = 0, max = 250, step = 1
    ),
    helpText("1 standard drink = 14 g alcohol.  Values above ~36 drinks/week
              (500 g) are capped at 500 g in line with the training data."),

    selectInput(
      inputId = "smoking",
      label   = "Smoking status",
      choices = c(
        "Non-current smoker (never / ex)" = "0",
        "Current smoker"                  = "1"
      )
    ),

    hr(),

    # actionButton() does nothing by itself — the server listens for clicks
    # via observeEvent(input$predict_btn, { … })
    actionButton(
      inputId = "predict_btn",
      label   = "Calculate Risk",
      class   = "btn-primary w-100"
    )
  ),

  # ── Right main panel: output placeholder ──────────────────────────────────
  # uiOutput() is an empty container that server fills in dynamically.
  # Before the button is clicked this area renders nothing.
  uiOutput("results_ui")
)


# ── 4.  Server ────────────────────────────────────────────────────────────────
server <- function(input, output, session) {

  # observeEvent() runs its code block whenever the named event fires.
  # Here: run the whole pipeline whenever the button is clicked.
  observeEvent(input$predict_btn, {

    # ── 4a. Input validation ──────────────────────────────────────────────────
    # Collect any problems into a character vector; if any exist, show them
    # inside the results panel and abort the rest of the pipeline with return().
    errors <- character(0)

    if (is.na(input$age) || input$age < 18 || input$age > 100)
      errors <- c(errors, "Age must be between 18 and 100 years.")

    if (is.na(input$bmi) || input$bmi < 10 || input$bmi > 70)
      errors <- c(errors, "BMI must be between 10 and 70 kg/m².")

    if (is.na(input$alcohol) || input$alcohol < 0)
      errors <- c(errors, "Alcohol intake cannot be negative.")

    if (length(errors) > 0) {
      output$results_ui <- renderUI({
        div(
          class = "alert alert-danger mt-3",
          strong("Please fix the following:"),
          tags$ul(lapply(errors, tags$li))
        )
      })
      return()   # stop here; do not run the model
    }

    # ── 4b. Wrap everything in a progress indicator ───────────────────────────
    # withProgress() shows a spinner / progress bar in the browser while the
    # R code inside { } is executing.  incProgress() advances the bar.
    withProgress(message = "Calculating …", value = 0, {

      # ── 4c. Build new-patient data frame ─────────────────────────────────
      # The RSF model was trained with these exact encodings:
      #   sex:            factor — 1 = Male, 2 = Female
      #   has_t2dm:       factor — 0 = No, 1 = Yes
      #   smoking_binary: factor — 0 = non-current, 1 = current
      #   alcohol_grams_week: numeric, capped at 500 g/week
      newdata_factors <- data.frame(
        age                = as.numeric(input$age),
        sex                = factor(ifelse(input$sex == "Male", 1L, 2L),
                                    levels = c(1L, 2L)),
        bmi                = as.numeric(input$bmi),
        has_t2dm           = factor(as.integer(input$t2dm),
                                    levels = c(0L, 1L)),
        alcohol_grams_week = min(as.numeric(input$alcohol) * 14, 500),
        smoking_binary     = factor(as.integer(input$smoking),
                                    levels = c(0L, 1L))
      )

      incProgress(0.2, detail = "Running survival model …")

      # ── 4d. Predict cumulative incidence ──────────────────────────────────
      # predict() on an rfsrc object returns a list containing:
      #   $time.interest : all unique event times the forest knows about
      #   $cif[i, t, k]  : cumulative incidence for patient i, at time index t,
      #                     for cause k (1 = MALO, 2 = competing non-liver death)
      pred <- predict(model, newdata = newdata_factors)

      # which.min(abs(…)) finds the stored time point *closest* to 5 or 10 yrs
      t5_idx  <- which.min(abs(pred$time.interest - 5))
      t10_idx <- which.min(abs(pred$time.interest - 10))

      risk_5  <- round(pred$cif[1, t5_idx,  1] * 100, 2)   # as percentage
      risk_10 <- round(pred$cif[1, t10_idx, 1] * 100, 2)

      incProgress(0.3, detail = "Computing SHAP values …")

      # ── 4e. SHAP for top modifiable risk factor ───────────────────────────
      # SHAP (SHapley Additive exPlanations) assigns each feature a score that
      # measures how much *that feature alone* shifted this patient's predicted
      # 10-year risk compared with an average patient from the background data.
      # Positive = raises risk; negative = lowers risk.
      #
      # kernelshap() is model-agnostic Kernel SHAP.  We supply a custom
      # pred_fun that re-encodes the numeric columns back into factors before
      # passing them to the RSF model.  bg_X is the numeric background sample
      # used to integrate out each feature's marginal contribution.

      predict_rsf_10yr <- function(object, X) {
        X$sex            <- factor(as.integer(round(X$sex)),
                                   levels = c(1L, 2L))
        X$has_t2dm       <- factor(as.integer(round(X$has_t2dm)),
                                   levels = c(0L, 1L))
        X$smoking_binary <- factor(as.integer(round(X$smoking_binary)),
                                   levels = c(0L, 1L))
        p     <- predict(object, newdata = X)
        t10_i <- which.min(abs(p$time.interest - 10))
        p$cif[, t10_i, 1]        # numeric vector, one value per row of X
      }

      # All-numeric copy of the patient row (kernelshap requires no factors)
      newdata_num <- newdata_factors
      newdata_num[] <- lapply(newdata_num, function(x) as.numeric(as.character(x)))

      # kernelshap() returns an object; $S is a matrix with one row per patient
      # and one column per predictor holding the Kernel SHAP value.
      ks <- kernelshap(
        object   = model,
        X        = as.data.frame(newdata_num),
        bg_X     = background,
        pred_fun = predict_rsf_10yr,
        verbose  = FALSE
      )

      shap_dt <- as.data.frame(ks$S)

      # Consider only the four MODIFIABLE predictors (exclude age, sex)
      modifiable_vars <- c("bmi", "has_t2dm", "alcohol_grams_week", "smoking_binary")
      var_labels <- c(
        bmi                = "BMI",
        has_t2dm           = "Type 2 diabetes",
        alcohol_grams_week = "Alcohol intake",
        smoking_binary     = "Smoking status"
      )

      # Subset to modifiable columns and find the largest absolute SHAP value
      mod_cols      <- intersect(names(shap_dt), modifiable_vars)
      mod_shap      <- as.numeric(shap_dt[1, mod_cols])
      names(mod_shap) <- mod_cols

      top_idx       <- which.max(abs(mod_shap))
      top_var_raw   <- names(mod_shap)[top_idx]
      top_var_label <- var_labels[[top_var_raw]]
      top_shap_val  <- mod_shap[top_idx]
      shap_direction <- ifelse(top_shap_val > 0,
                               "increases this patient's risk",
                               "decreases this patient's risk")

      incProgress(0.5, detail = "Preparing output …")

      # ── 4f. Risk category and recommendation ──────────────────────────────
      high_risk     <- risk_10 >= 0.5
      risk_category <- ifelse(high_risk, "High Risk", "Low Risk")
      threshold_txt <- ifelse(high_risk, "≥ 0.5%", "< 0.5%")
      card_colour   <- ifelse(high_risk, "danger", "success")
      surveillance  <- if (high_risk) {
        "Repeat FIB-4 assessment every 1–2 years (intensified surveillance)"
      } else {
        "Repeat FIB-4 assessment every 3 years (standard surveillance)"
      }

      incProgress(1.0)

      # ── 4g. Build the output UI ───────────────────────────────────────────
      # renderUI() lets server construct arbitrary HTML/Shiny widgets at
      # run-time and push them into the uiOutput("results_ui") placeholder.
      # layout_columns() / card() / card_header() / card_body() come from bslib.
      output$results_ui <- renderUI({
        tagList(

          hr(),

          layout_columns(
            col_widths = c(5, 7),

            # ── Card 1: predicted risk numbers ──────────────────────────────
            card(
              height = "100%",
              card_header(
                class = "fw-semibold",
                "Predicted Risk of Major Adverse Liver Outcomes"
              ),
              card_body(
                tags$table(
                  class = "table table-sm table-borderless mb-0",
                  tags$tbody(
                    tags$tr(
                      tags$th("5-year risk:"),
                      tags$td(strong(paste0(risk_5, "%")))
                    ),
                    tags$tr(
                      tags$th("10-year risk:"),
                      tags$td(strong(paste0(risk_10, "%")))
                    )
                  )
                )
              )
            ),

            # ── Card 2: risk category + recommendation ───────────────────────
            card(
              height = "100%",
              card_header(
                class = paste0("bg-", card_colour, " text-white fw-semibold"),
                paste0("Risk Category: ", risk_category,
                       "  (10-year risk ", threshold_txt, ")")
              ),
              card_body(
                p(
                  strong("Primary Modifiable Risk Factor: "),
                  top_var_label,
                  " — this factor ", shap_direction,
                  " the most among modifiable variables."
                ),
                hr(class = "my-2"),
                p(strong("Recommendation: "), surveillance)
              )
            )
          ) # end layout_columns
        )   # end tagList
      })    # end renderUI

    }) # end withProgress
  })   # end observeEvent
}


# ── 5.  Launch ────────────────────────────────────────────────────────────────
shinyApp(ui = ui, server = server)
